export interface Product {
	slug: string
	name: string
	price?: string
	image: string
	rating: number
	reviews: number
	features: string[]
	badge: string
	amazonLink: string
	description: string
	specifications: {
		[key: string]: string
	}
	// Air fryer specific fields
	capacity?: string
	presets?: number
	wattage?: string
	tempRange?: string
}

export const multicookerProducts: Product[] = [
	{
		slug: "ninja-mc1001-foodi",
		name: "Ninja MC1001",
		price: "",
		image: "https://m.media-amazon.com/images/I/61-hMn0AQsL._AC_SY300_SX300_QL70_FMwebp_.jpg",
		rating: 4.7,
		reviews: 4893,
		features: ["Ninja", "8.5 Quarts", "Aluminum", "Sea Salt Gray", "825 watts", '18"D x 12.64"W x 10.59"H'],
		badge: "Premium",
		amazonLink: "https://www.amazon.com/Ninja-MC1001-PossibleCooker-Multi-Cooker-Integrated/dp/B0B4PPHG8G",
		description:
			"The Ninja MC1001 Foodi PossibleCooker PRO is a revolutionary 8-in-1 multi-cooker that combines the functionality of multiple kitchen appliances into one powerful device. With its generous 8.5-quart capacity, this premium multicooker is perfect for families and meal prep enthusiasts. The integrated smart control system allows you to monitor and adjust cooking settings with precision, ensuring perfect results every time. The stainless steel construction provides durability and easy cleaning, while the 15 pre-programmed cooking functions cover everything from slow cooking and pressure cooking to sautéing and steaming. Whether you're preparing a quick weeknight dinner or an elaborate weekend feast, the Ninja Foodi PossibleCooker PRO delivers consistent, delicious results with minimal effort.",
		specifications: {
			Brand: "Ninja",
			Model: "MC1001 Foodi PossibleCooker PRO",
			Capacity: "8.5 Quarts",
			Material: "Aluminum Construction",
			Color: "Sea Salt Gray",
			Dimensions: '18"D x 12.64"W x 10.59"H',
			"Power Output": "825 Watts",
			"Cooking Functions": "8-in-1 Multi-Cooker (Pressure Cook, Slow Cook, Sauté, Steam, Sear, Bake, Roast, Broil)",
			"Control Type": "Integrated Smart Control System",
			"Inner Pot": "Non-Stick Aluminum Pot",
			"Temperature Range": "Low to High Heat Settings",
			"Safety Features": "Lid Lock, Pressure Release Valve, Overheat Protection",
			Warranty: "1 Year Limited Warranty",
			"Ideal For": "Families, Meal Prep, Multi-Function Cooking",
		},
	},
	{
		slug: "chef-iq",
		name: "CHEF iQ Smart Pressure Cooker",
		image: "https://m.media-amazon.com/images/I/71qaNsaMkpL._AC_SX679_.jpg",
		rating: 4.8,
		reviews: 892,
		features: [
			"CHEF iQ",
			"6 Quarts Capacity",
			"Aluminum / ABS & PP Plastic",
			"Black Matte Finish",
			"13\" D × 13\" W × 13\" H"
		],
		badge: "Limited Time Deal",
		amazonLink: "https://www.amazon.com/CHEF-Worlds-Smartest-Pressure-Cooker/dp/B0863JB424",
		description:
			"The CHEF iQ Smart Pressure Cooker combines intelligent technology with powerful performance to simplify everyday cooking. Featuring built-in WiFi connectivity and app integration, it lets you monitor, adjust, and receive step-by-step cooking guidance directly from your smartphone. Its 6-quart capacity makes it ideal for small families or couples, while the nonstick aluminum pot ensures easy food release and effortless cleaning. With multiple preset cooking programs — from slow cook and pressure cook to sauté, yogurt, and steam — this device delivers precision results with minimal effort. The digital interface and smart sensors automatically regulate time, temperature, and pressure for consistent performance. Designed with a sleek matte black finish, it adds a modern touch to any kitchen.",
		specifications: {
			Brand: "CHEF iQ",
			Model: "Smart WiFi Pressure Cooker (ASIN B0863JB424)",
			Capacity: "6 Quarts (suitable for 2–4 servings)",
			Material: "Durable Aluminum Inner Pot with ABS and PP Plastic Housing",
			Color: "Matte Black",
			Dimensions: "13\" D × 13\" W × 13\" H",
			Weight: "Approx. 12.5 lbs",
			PowerOutput: "1000 Watts",
			Voltage: "120 Volts",
			SmartFeatures: "Built-in WiFi, App Control, Guided Cooking, and Recipe Updates",
			CookingFunctions: "Pressure Cook, Slow Cook, Steam, Sauté, Rice, Yogurt, Soup, Stew, Porridge, Reheat, Keep Warm",
			Display: "Full Digital Touchscreen with LED Status Indicators",
			ControlType: "Smart One-Touch Panel with App Integration",
			InnerPot: "Nonstick Aluminum Pot, Dishwasher Safe",
			SafetyFeatures: "Auto Pressure Release, Lid Lock System, Temperature Sensor, and Auto Shut-Off",
			Connectivity: "2.4GHz WiFi connection for mobile control via CHEF iQ App",
			IdealFor: "Smart kitchens, couples, and small households",
			Warranty: "2-Year Limited Manufacturer Warranty"
		}
	},
	{
		slug: "iris-living",
		name: "IRIS LIVING 2-in-1 Rice Cooker",
		image: "https://m.media-amazon.com/images/I/71QPsXAd6SL._AC_SX679_.jpg",
		rating: 4.5,
		reviews: 634,
		features: [
			"IRIS LIVING",
			"1000 Watts",
			"3 Cups Capacity",
			"Aluminum",
			"Black",
			"11.02 x 8.86 x 8.66 inches"
		],
		badge: "Portable and Compact",
		amazonLink: "https://www.amazon.com/dp/B0C6M4V6LX",
		description:
			"Compact yet remarkably versatile, the IRIS LIVING 2-in-1 Rice Cooker and Induction Cooktop transforms small-space cooking into a smooth, efficient process. This sleek countertop unit unites the convenience of an induction burner with the precision of a modern rice cooker, delivering fast, even heating across a durable nonstick pot. Its intuitive digital interface lets you simmer, steam, or fry with total control, while the 1000-watt power output ensures consistent performance. Designed for portability, the lightweight housing stays cool to the touch and fits easily in dorms, RVs, or compact kitchens. Cleaning is effortless thanks to the removable inner bowl, and built-in safeguards like automatic shut-off and temperature protection enhance everyday safety. Whether preparing rice, soups, or quick one-pan meals, this space-saving appliance provides smart functionality and elegant simplicity in a single device.",
		specifications: {
			Brand: "IRIS LIVING",
			Model: "RC-IH30 / 2-in-1 Induction Rice Cooker",
			Capacity: "3 Cups Uncooked (6 Cups Cooked)",
			Material: "Nonstick Aluminum Bowl with Even Heat Distribution",
			Color: "Black",
			Dimensions: "11.02 x 8.86 x 8.66 inches",
			Weight: "Approx. 6.4 lbs",
			PowerOutput: "1000 Watts",
			Voltage: "120 Volts",
			CookingFunctions: "Rice Cooking, Steaming, Boiling, Induction Frying",
			CooktopType: "Induction Heating Technology",
			ControlType: "Digital Touch Interface with LED Screen",
			Portability: "Compact, Lightweight, and Travel-Friendly Design",
			InnerPot: "Removable Nonstick Aluminum Pot, Dishwasher Safe",
			SafetyFeatures: "Automatic Shut-Off, Overheat Protection, Cool-Touch Exterior",
			AccessoriesIncluded: "Measuring Cup, Steam Tray, Rice Spatula",
			IdealFor: "Apartments, Dorms, RVs, and Small Kitchens",
			Warranty: "1-Year Limited Warranty"
		}
	},
	{
		slug: "magnifique-experience-delight",
		name: "MAGNIFIQUE EXPERIENCE DELIGHT 4-Quart Multi-Cooker",
		image: "https://m.media-amazon.com/images/I/61Ko1tp3AXL._AC_SX679_.jpg",
		rating: 4.4,
		reviews: 543,
		features: [
			"MAGNIFIQUE EXPERIENCE DELIGHT",
			"1130 Watts",
			"4 Quarts Capacity",
			"Aluminum Construction",
			"Brown Finish",
			"13\" D × 16\" W × 7\" H"
		],
		badge: "Vintage Design",
		amazonLink: "https://www.amazon.com/dp/B0DMWPLW1Y",
		description:
			"The MAGNIFIQUE EXPERIENCE DELIGHT Multi-Cooker combines vintage-inspired aesthetics with modern cooking precision. Offering multiple preset programs for stews, rice, soups, and sautéing, it simplifies everyday meal preparation. Its PFAS-free ceramic-coated pot ensures safe cooking and easy cleaning, while the porcelain liner withstands heat up to 450°F. Designed for families, it accommodates up to 4 pounds of food — perfect for small gatherings or daily dinners. With an 1130-watt output, smooth digital interface, and cool-touch handles, this cooker blends performance, safety, and style into one elegant appliance.",
		specifications: {
			Brand: "MAGNIFIQUE EXPERIENCE DELIGHT",
			Model: "4-Quart Digital Multi-Cooker",
			Capacity: "4 Quarts (Suitable for 4+ Servings)",
			Material: "Aluminum Housing with Ceramic Nonstick Interior",
			Color: "Brown",
			Dimensions: "13\" D × 16\" W × 7\" H",
			Weight: "Approx. 19 lbs",
			PowerOutput: "1130 Watts",
			Voltage: "120 Volts",
			CookingFunctions: "Slow Cook, Sauté, Braise, Keep Warm, Brown Rice, White Rice, Oats, Pasta",
			PotType: "Removable Ceramic Pot, Dishwasher Safe and Oven Safe up to 450°F",
			ControlPanel: "Digital Touch Display with One-Touch Presets",
			SafetyFeatures: "Cool-Touch Handles, Auto Shut-Off, Overheat Protection",
			Design: "Retro-Inspired Finish with Modern Digital Interface",
			IdealFor: "Family Dinners, Potlucks, and Everyday Cooking",
			Warranty: "1-Year Limited Warranty"
		}
	},
	{
		slug: "black-decker",
		name: "BLACK+DECKER 7-Quart Family Multicooker",
		image: "https://m.media-amazon.com/images/I/71vKIhnX-BL._AC_SX679_.jpg",
		rating: 4.9,
		reviews: 421,
		features: [
			"BLACK+DECKER",
			"800 Watts",
			"7 Quarts Capacity",
			"Ceramic Nonstick Surface",
			"Black Finish",
			"18.35\" D × 8.74\" W × 13.5\" H"
		],
		badge: "Family Size",
		amazonLink: "https://www.amazon.com/dp/B0F6RQM7SC",
		description:
			"This 7-quart family-sized multicooker from BLACK+DECKER merges five essential cooking functions into one sleek countertop unit. With its PFAS-free ceramic non-stick pot and dishwasher-safe lid, cleanup is effortless. From browning meats or veggies with sauté/sear to gentle slow-cooking and rice preparation, it adapts to your meal workflow with ease. The control panel is detachable for extra convenience, while cool-touch handles and a steaming/roasting rack enable safe, multi-style cooking. Ideal for dinners, hearty soups and side dishes, this appliance brings flexible performance to family kitchens.",
		specifications: {
			Brand: "BLACK+DECKER",
			Model: "MC900MADX (ASIN B0F6RQM7SC)",
			Capacity: "7 Quarts (approximately 6.6 Liters)",
			PowerOutput: "800 Watts",
			Voltage: "120 Volts",
			Color: "Black",
			Dimensions: "18.35\" D × 8.74\" W × 13.5\" H",
			Material: "PFAS-free Ceramic Nonstick Pot with Dishwasher-Safe Lid",
			CookingFunctions: "Slow Cook, Steam/Boil, Precision Roast, Sear/Sauté, and Rice",
			Technology: "Neat ‘N Clean™ removable control panel for easy washing",
			CoolTouchHandles: "Yes, designed for safe and comfortable handling",
			AccessoriesIncluded: "Steaming/Roasting Rack",
			SafetyFeatures: "Cool-touch exterior, overheat protection, automatic shutoff",
			IdealFor: "Family-size meals, soups, side dishes, and desserts",
			Warranty: "2-Year Limited Warranty"
		}
	},
	{
		slug: "instant-pot-duo-7in1",
		name: "Instant Pot Duo 7-in-1 Multi-Use Pressure Cooker",
		image: "https://m.media-amazon.com/images/I/71Z401LjFFL._AC_SX679_.jpg",
		rating: 4.6,
		reviews: 180587,
		features: [
			"7-in-1 Functionality",
			"6 Quart / ≈5.7 L Capacity",
			"1000 Watts Power",
			"Stainless Steel Inner Pot",
			"12.2\" D × 13.38\" W × 12.48\" H",
			"11.8 lbs Weight"
		],
		badge: "Best Seller",
		amazonLink: "https://www.amazon.com/dp/B00FLYWNYQ",
		description:
			"The Instant Pot Duo 7-in-1 Multi-Use Pressure Cooker brings together seven key cooking modes in one sleek appliance. Designed with a spacious 6-quart (≈5.7 L) stainless-steel pot and intuitive digital controls, it handles pressure cooking, slow cooking, rice, steaming, sautéing, yogurt, and warming with ease. The tri-ply bottom pot ensures even heat distribution while the dishwasher-safe parts make cleanup simple. With robust safety features and built-in Smart Programs, this cooker is engineered for busy households who want one device to do it all.",
		specifications: {
			Brand: "Instant Pot",
			Model: "Duo 7-in-1 (ASIN B00FLYWNYQ)",
			Capacity: "6 Quarts (≈5.7 Litres)",
			Material: "18/8 Stainless Steel Inner Pot with Tri-Ply Bottom",
			Color: "Silver / Black",
			Dimensions: "12.2\" D × 13.38\" W × 12.48\" H",
			Weight: "Approx. 11.8 lbs",
			PowerOutput: "1000 Watts",
			Voltage: "120 Volts",
			CookingPrograms: "Up to 14 Smart-Programs (Soup/Broth, Meat/Stew, Bean/Chili, Slow Cook, Sauté, Rice, Porridge, Steam, Yogurt, Keep Warm, Pressure Cook, Multigrain, Poultry)",
			Functions: "Pressure Cooking, Slow Cooking, Rice/Grain, Steaming, Sautéing, Yogurt Making, Warming",
			SafetyFeatures: "Lid Locking Mechanism, Overheat Protection, Pressure Sensor, Automatic Keep-Warm",
			IdealFor: "Families, Meal Prep, One-Pot Kitchens",
			Warranty: "1-Year Limited Manufacturer Warranty"
		}
	},
	{
		slug: "tiger-col-a40u",
		name: "Tiger COL-A40U Multi-Cooker",
		image: "https://m.media-amazon.com/images/I/71GvrNP-esL._AC_SX679_.jpg",
		rating: 4.8,
		reviews: 612,
		features: [
			"2.6-Quart Capacity (2.5 L)",
			"21 Auto-Set Menus + 8 Manual Modes",
			"Self-Cleaning Function",
			"Compact 760 W Design"
		],
		badge: "Compact Multi-Use",
		amazonLink: "https://www.amazon.com/Tiger-COL-A40U-2-6-Quart-Multi-Cooker-Programmed/dp/B0DQ9RW7HB",
		description:
			"The Tiger COL-A40U 2.6 Quart Compact Multi-Cooker delivers smart, space-saving cooking power in a portable size. Combining 21 automatic menu settings with 8 manual modes, it handles everything from soups and stews to rice, sous-vide, and oatmeal. The intuitive control dial simplifies operation — just select your program and let the appliance manage time and temperature automatically. A unique self-cleaning cycle helps eliminate odors and residue after use, while the detachable parts make cleanup quick and effortless. Compact yet capable, this multi-cooker is perfect for singles, couples, and smaller kitchens.",
		specifications: {
			Brand: "Tiger Corporation",
			Model: "COL-A40U (ASIN B0DQ9RW7HB)",
			Capacity: "2.5 Liters (≈ 2.6 Quarts)",
			PowerOutput: "760 Watts",
			Voltage: "120 Volts / 60 Hz",
			Material: "Plastic Housing / Non-Stick Aluminum Inner Pot",
			Color: "Black / Dark Gray",
			Dimensions: "12.76\" D × 12.56\" W × 9.8\" H",
			Weight: "Approx. 7.5 lbs (3.4 kg)",
			CookingPrograms: "21 Preset Menus + 8 Manual Cooking Modes",
			CookingFunctions: "Rice, Slow Cook, Steam, Sauté, Quinoa, Sous Vide, Oatmeal, Keep Warm and More",
			SpecialFeature: "Self-Cleaning Mode for Automatic Odor and Residue Removal",
			ControlType: "Rotary Dial Selector with Digital Menu Display",
			SafetyFeatures: "UL Certified, Pressure Control Cap, Auto Shut-Off, Overheat Protection",
			AccessoriesIncluded: "Inner Pot, Condensation Collector, Pressure Control Cap, Power Cord",
			IdealFor: "Singles, Couples, Dorm Rooms, Compact Living Spaces",
			Warranty: "1-Year Limited Manufacturer Warranty"
		}
	},
	{
		slug: "sunvivi-multicooker-6-5qt",
		name: "Sunvivi 12-in-1 Multi-Cooker",
		image: "https://m.media-amazon.com/images/I/713qpoRM4uL._AC_SX679_.jpg",
		rating: 4.3,
		reviews: 309,
		features: [
			"6.5 Quart Capacity (≈6.2 L)",
			"12 Preset Cooking Modes",
			"Removable Non-Stick Inner Pot",
			"Digital Timer and Temperature Control",
			"Dishwasher-Safe Glass Lid"
		],
		badge: "All-in-One",
		amazonLink: "https://www.amazon.com/Sunvivi-Programmable-Removable-Nonstick-Multicooker/dp/B0DPG69TBD",
		description:
			"This Sunvivi 12-in-1 Multi-Cooker offers robust versatility for your kitchen — with a generous 6.5-quart capacity and preset modes that take care of everything from slow cooking and roasting to rice and steamed dishes. A smart digital panel and separate temperature control make operation intuitive, while the removable nonstick inner bowl and dishwasher-safe glass lid simplify cleanup. Whether you’re prepping meals for the week, entertaining guests or just want one appliance that does it all, this model delivers convenience, flexibility and performance in one compact unit.",
		specifications: {
			Brand: "Sunvivi",
			Model: "12-in-1 Multi-Cooker (ASIN B0DPG69TBD)",
			Capacity: "6.5 Quarts (≈6.2 Litres)",
			PowerOutput: "1250 Watts",
			Voltage: "120 Volts",
			Material: "Metal Housing with Removable Non-Stick Inner Pot and Glass Lid",
			Color: "Silver / Stainless",
			Dimensions: "16.9\" D × 10\" W × 11\" H",
			Weight: "Approx. 12.23 lbs",
			CookingPrograms: "12 Auto Settings for Bake, Roast, Saute, Slow-Cook, Rice, Yogurt, Sous-Vide, and More",
			ControlType: "Digital Timer & Temp Control Panel",
			InnerPot: "Removable Nonstick Pot, Dishwasher Safe Glass Lid",
			SafetyFeatures: "Cool-Touch Handles, Lid Lock, Overheat Protection",
			IdealFor: "Families, Meal-Prep, Multi-Function Use",
			Warranty: "1-Year Limited Warranty"
		}
	},
	{
		slug: "nuwave-combi-steam-oven-16qt",
		name: "NUWAVE Combi Steam Oven Multi-Cooker",
		image: "https://m.media-amazon.com/images/I/81rD--bKYNL._AC_SX679_.jpg",
		rating: 4.4,
		reviews: 11070,
		features: [
			"16 Qt Extra-Large Capacity",
			"Steam + Air Fry Combination",
			"50°F–450°F Precision Temperature",
			"120 Cooking Presets + Custom Memory"
		],
		badge: "Premium",
		amazonLink: "https://www.amazon.com/Nuwave-Steam-Oven-Stainless-Multi-Cooker/dp/B0DSQ8PWPJ",
		description:
			"The NUWAVE Combi Steam Oven delivers professional-grade cooking at home by blending powerful steam output with rapid air-circulation technology. This results in tender, juicy dishes with crisp, golden finishes — all in a single appliance. With a spacious 16-quart interior, you can prepare full family meals, bake pastries, air fry snacks, or slow-steam large proteins with ease. The wide 50 °F to 450 °F temperature range supports everything from gentle sous-vide style cooking to high-heat roasting. Adjustable humidity levels allow precise steam control, helping breads rise properly and proteins stay moist. Featuring 120 built-in cooking presets plus slots for your own custom settings, this oven simplifies everyday meal prep. Its stainless-steel, non-toxic interior wipes clean easily, and all included accessories are dishwasher-safe for hassle-free maintenance.",
		specifications: {
			Brand: "NUWAVE",
			Model: "Combi Steam Oven 16 Qt",
			Capacity: "16 Quarts (Family Size)",
			Material: "Stainless Steel Interior & Exterior",
			Color: "Stainless Steel",
			"Temperature Range": "50 °F – 450 °F",
			"Moisture Control": "Adjustable Steam Infusion (10%–90%)",
			"Cooking Presets": "120 Built-In Programs + Custom Memory Options",
			"Cooking Functions":
				"Steam, Air Fry, Steam + Air Fry Combo, Roast, Bake, Toast, Reheat, Sous-Vide-Style Low Temp Cooking",
			"Control Type": "Digital Touch Panel with LED Indicators",
			"Power Output": "High-Performance Heating System (~1800W Class)",
			Dimensions: "14.75\"D × 13.88\"W × 14.88\"H",
			"Accessories Included": "Air Fry Basket, Stainless Tray, Cooking Rack, Drip Tray, Water Tank (Dishwasher-Safe)",
			"Safety Features": "Door Interlock, Auto Shut-Off, Overheat Protection",
			"Ideal For":
				"Healthy Steam Cooking, Crispy Air Frying, Bread & Pastry Baking, Family-Size Meals, All-in-One Kitchen Use"
		}
	}
]

export const airFryerProducts: Product[] = [
	{
		slug: "airchef-pro-5-5l",
		name: "AirChef Pro 5.5L",
		price: "$129.99",
		image: "/modern-multicooker-on-kitchen-counter.jpg",
		rating: 4.8,
		reviews: 856,
		capacity: "5.5L",
		presets: 8,
		features: ["5.5L Capacity", "Digital Display", "8 Presets", "Dishwasher Safe"],
		badge: "Best Seller",
		wattage: "1700W",
		tempRange: "80-200°C",
		amazonLink: "https://www.amazon.com",
		description:
			"The AirChef Pro 5.5L is our best-selling air fryer, combining generous capacity with user-friendly features that make healthy cooking effortless. With its 5.5-liter basket, you can prepare meals for 4-5 people in one go, making it perfect for families. The intuitive digital display provides precise control over temperature and timing, while 8 pre-programmed presets take the guesswork out of cooking your favorite foods. The non-stick basket is dishwasher safe for easy cleanup, and the compact footprint won't take up too much counter space. Whether you're making crispy french fries, juicy chicken wings, or roasted vegetables, theAirChef Pro delivers consistent, delicious results with up to 85% less oil than traditional frying methods.",
		specifications: {
			Brand: "AirChef",
			Model: "Pro 5.5L",
			Capacity: "5.5 Liters (5.8 Quarts)",
			Display: "Digital Display",
			"Cooking Presets": "8 Presets",
			"Dishwasher Safe": "Yes - Basket is Dishwasher Safe",
			"Power Output": "1700 Watts",
			"Temperature Range": "80°C - 200°C (176°F - 392°F)",
			Dimensions: "12 x 12 x 13 inches",
			"Preset Functions": "Fries, Chicken, Steak, Shrimp, Fish, Pizza, Vegetables, Bake",
			"Basket Material": "Non-Stick Coated Aluminum",
			"Control Type": "Digital Touch Controls",
			Timer: "60-Minute Timer with Auto Shut-Off",
			"Cooking Technology": "Rapid Air Circulation System",
			"Safety Features": "Auto Shut-Off, Cool-Touch Handle",
			Warranty: "2 Years Limited Warranty",
			"Ideal For": "Families, Best-Selling Model, Easy Cleanup",
		},
	},
	{
		slug: "airchef-compact-3-5l",
		name: "AirChef Compact 3.5L",
		price: "$89.99",
		image: "/compact-multicooker-6-liter-red.jpg",
		rating: 4.7,
		reviews: 623,
		capacity: "3.5L",
		presets: 6,
		features: ["3.5L Capacity", "Touch Control", "6 Presets", "Compact Design"],
		badge: "Budget Pick",
		wattage: "1400W",
		tempRange: "80-200°C",
		amazonLink: "https://www.amazon.com",
		description:
			"The AirChef Compact 3.5L is the perfect entry-level air fryer for singles, couples, or anyone with limited kitchen space. Despite its compact size, this budget-friendly model doesn't compromise on performance, delivering crispy, delicious results every time. The sleek touch control panel makes operation simple and intuitive, while 6 essential cooking presets cover all your basic air frying needs. The 3.5-liter capacity is ideal for preparing meals for 1-2 people, and the compact design means it won't take up valuable counter space. The energy-efficient 1400W heating element provides fast, even cooking, while the removable basket makes cleanup a breeze. If you're new to air frying or looking for an affordable option that delivers great results, the Compact 3.5L is an excellent choice.",
		specifications: {
			Brand: "AirChef",
			Model: "Compact 3.5L",
			Capacity: "3.5 Liters (3.7 Quarts)",
			"Control Type": "Touch Control",
			"Cooking Presets": "6 Presets",
			Design: "Compact Design",
			"Power Output": "1400 Watts",
			"Temperature Range": "80°C - 200°C (176°F - 392°F)",
			Dimensions: "10 x 10 x 11 inches (Compact)",
			"Preset Functions": "Fries, Chicken, Fish, Vegetables, Bake, Reheat",
			Display: "Touch Control Panel with LED Indicators",
			"Basket Material": "Non-Stick Coating, BPA-Free",
			Timer: "30-Minute Timer",
			"Safety Features": "Auto Shut-Off, Overheat Protection",
			Warranty: "1 Year Limited Warranty",
			"Ideal For": "Singles, Couples, Small Kitchens, Budget-Friendly",
		},
	},
	{
		slug: "airchef-xl-7l",
		name: "AirChef XL 7L",
		price: "$179.99",
		image: "/large-professional-multicooker-8-liter-stainless-s.jpg",
		rating: 4.9,
		reviews: 1034,
		capacity: "7L",
		presets: 12,
		features: ["7L Capacity", "Smart Control", "12 Presets", "Dual Basket"],
		badge: "Premium",
		wattage: "1800W",
		tempRange: "50-230°C",
		amazonLink: "https://www.amazon.com",
		description:
			"The AirChef XL 7L represents the pinnacle of air frying technology, offering premium features and exceptional versatility for serious home cooks. The generous 7-liter capacity with dual basket design allows you to cook two different foods simultaneously at different temperatures, perfect for preparing complete meals in one go. Smart control technology with 12 pre-programmed presets ensures perfect results every time, while the extended temperature range from 50-230°C opens up new cooking possibilities including dehydrating and slow cooking. The powerful 1800W heating element provides rapid, even heat distribution for consistently crispy results. Premium construction with stainless steel accents and a sleek design makes this air fryer a beautiful addition to any kitchen. If you're looking for the ultimate air frying experience with maximum versatility, the XL 7L is your perfect choice.",
		specifications: {
			Brand: "AirChef",
			Model: "XL 7L",
			Capacity: "7 Liters Total (3.5L + 3.5L Dual Baskets)",
			"Control Type": "Smart Control",
			"Cooking Presets": "12 Presets",
			"Special Feature": "Dual Basket",
			"Power Output": "1800 Watts",
			"Temperature Range": "50°C - 230°C (122°F - 446°F)",
			Dimensions: "14 x 13 x 14 inches",
			"Preset Functions":
				"Fries, Chicken, Steak, Shrimp, Fish, Pizza, Vegetables, Bake, Roast, Dehydrate, Reheat, Keep Warm",
			"Dual Basket Feature": "Cook 2 Foods Simultaneously at Different Temperatures",
			Display: "Dual Digital Displays for Independent Control",
			"Basket Material": "Premium Non-Stick with Stainless Steel Accents",
			"Sync Function": "Finish Both Baskets at Same Time",
			"Safety Features": "Dual Auto Shut-Off, Cool-Touch Handles",
			Warranty: "3 Years Premium Warranty",
			"Ideal For": "Premium Cooking, Dual Zone, Complete Meals",
		},
	},
	{
		slug: "airchef-mini-2-5l",
		name: "AirChef Mini 2.5L",
		price: "$69.99",
		image: "/compact-multicooker-6-liter-red.jpg",
		rating: 4.6,
		reviews: 412,
		capacity: "2.5L",
		presets: 5,
		features: ["2.5L Capacity", "Manual Control", "5 Presets", "Space Saving"],
		badge: "Compact",
		wattage: "1200W",
		tempRange: "80-200°C",
		amazonLink: "https://www.amazon.com",
		description:
			"The AirChef Mini 2.5L is the ultimate space-saving solution for small kitchens, dorm rooms, or RVs. This ultra-compact air fryer may be small in size, but it delivers big on performance and convenience. The 2.5-liter capacity is perfect for preparing individual portions or small meals for one person, making it ideal for singles or those living alone. Simple manual controls make operation straightforward, while 5 essential presets cover the most popular air frying applications. The compact footprint means you can easily store it in a cabinet when not in use, and the lightweight design makes it portable enough to take with you on trips. Despite its affordable price point, the Mini 2.5L doesn't compromise on quality, featuring a durable non-stick basket and reliable heating element that delivers consistent results.",
		specifications: {
			Brand: "AirChef",
			Model: "Mini 2.5L",
			Capacity: "2.5 Liters (2.6 Quarts)",
			"Control Type": "Manual Control",
			"Cooking Presets": "5 Presets",
			Design: "Space Saving",
			"Power Output": "1200 Watts",
			"Temperature Range": "80°C - 200°C (176°F - 392°F)",
			Dimensions: "9 x 9 x 10 inches (Ultra-Compact)",
			Weight: "6 lbs (Lightweight & Portable)",
			"Preset Functions": "Fries, Chicken, Fish, Vegetables, Reheat",
			Display: "Simple Manual Dial Controls",
			"Basket Material": "Non-Stick Coating",
			Timer: "30-Minute Mechanical Timer",
			Portability: "Lightweight Design for Travel",
			"Safety Features": "Auto Shut-Off, Heat-Resistant Handle",
			Warranty: "1 Year Limited Warranty",
			"Ideal For": "Singles, Dorm Rooms, RVs, Space-Saving",
		},
	},
	{
		slug: "airchef-family-9l",
		name: "AirChef Family 9L",
		price: "$219.99",
		image: "/large-professional-multicooker-8-liter-stainless-s.jpg",
		rating: 4.9,
		reviews: 789,
		capacity: "9L",
		presets: 15,
		features: ["9L Capacity", "WiFi Control", "15 Presets", "Triple Basket"],
		badge: "Family Size",
		wattage: "2000W",
		tempRange: "40-230°C",
		amazonLink: "https://www.amazon.com",
		description:
			"The AirChef Family 9L is specifically engineered for large families and those who love to entertain. With its massive 9-liter capacity and innovative triple basket design, you can cook three different foods simultaneously, making meal preparation faster and more efficient than ever. WiFi connectivity allows you to control and monitor your cooking from anywhere using your smartphone, receiving notifications when your food is ready. Fifteen versatile cooking presets cover everything from basic air frying to advanced techniques like rotisserie and dehydrating. The powerful 2000W heating element ensures even cooking throughout the large capacity, while the extended temperature range from 40-230°C provides maximum versatility. If you're tired of cooking in batches or need a reliable appliance for feeding a crowd, the Family 9L is your ultimate solution.",
		specifications: {
			Brand: "AirChef",
			Model: "Family 9L",
			Capacity: "9 Liters Total (3L + 3L + 3L Triple Baskets)",
			"Control Type": "WiFi Control",
			"Cooking Presets": "15 Presets",
			"Special Feature": "Triple Basket",
			"Power Output": "2000 Watts",
			"Temperature Range": "40°C - 230°C (104°F - 446°F)",
			Dimensions: "16 x 15 x 15 inches",
			"Smart Features": "WiFi Enabled, Smartphone App Control",
			"Preset Functions":
				"Fries, Chicken, Steak, Shrimp, Fish, Pizza, Vegetables, Bake, Roast, Rotisserie, Dehydrate, Proof, Reheat, Keep Warm, Broil",
			"Triple Basket Feature": "Cook 3 Different Foods Simultaneously",
			Display: "Triple Digital Displays with Color LCD",
			"Basket Material": "Premium Non-Stick, Dishwasher-Safe",
			"App Features": "Remote Control, Recipe Library, Notifications",
			"Safety Features": "Triple Auto Shut-Off, Cool-Touch Exterior",
			Warranty: "3 Years Family Warranty",
			"Ideal For": "Large Families, Entertaining, Multi-Zone Cooking",
		},
	},
	{
		slug: "airchef-smart-6l",
		name: "AirChef Smart 6L",
		price: "$159.99",
		image: "/modern-multicooker-on-kitchen-counter.jpg",
		rating: 4.8,
		reviews: 945,
		capacity: "6L",
		presets: 10,
		features: ["6L Capacity", "App Control", "10 Presets", "Voice Assistant"],
		badge: "Smart Home",
		wattage: "1750W",
		tempRange: "60-220°C",
		amazonLink: "https://www.amazon.com",
		description:
			"The AirChef Smart 6L brings your air fryer into the smart home era with advanced connectivity features and intelligent cooking technology. Control your air fryer using the dedicated smartphone app, allowing you to start, stop, and adjust cooking settings from anywhere in your home. Voice assistant compatibility means you can control your air fryer hands-free using Alexa or Google Assistant. The 6-liter capacity is perfect for families of 3-4, while 10 smart presets automatically adjust time and temperature for optimal results. The app provides access to hundreds of recipes with step-by-step instructions, and you can save your favorite custom settings for one-touch cooking. For tech-savvy home cooks who want the convenience of smart home integration, the Smart 6L is the perfect choice.",
		specifications: {
			Brand: "AirChef",
			Model: "Smart 6L",
			Capacity: "6 Liters (6.3 Quarts)",
			"Control Type": "App Control",
			"Cooking Presets": "10 Presets",
			"Special Feature": "Voice Assistant",
			"Power Output": "1750 Watts",
			"Temperature Range": "60°C - 220°C (140°F - 428°F)",
			Dimensions: "13 x 12 x 13 inches",
			"Smart Features": "WiFi, Bluetooth, App Control, Voice Assistant Integration",
			"Voice Control": "Compatible with Alexa, Google Assistant",
			Display: "Smart Touchscreen with Recipe Display",
			"Preset Functions": "Fries, Chicken, Steak, Fish, Pizza, Vegetables, Bake, Roast, Dehydrate, Reheat",
			"App Features": "500+ Recipes, Custom Programs, Cooking History",
			"Basket Material": "Smart Non-Stick with Temperature Sensors",
			"Safety Features": "Smart Auto Shut-Off, Remote Monitoring",
			Warranty: "2 Years Smart Home Warranty",
			"Ideal For": "Smart Home Integration, App Control, Voice Commands",
		},
	},
	{
		slug: "airchef-turbo-5l",
		name: "AirChef Turbo 5L",
		price: "$139.99",
		image: "/modern-multicooker-on-kitchen-counter.jpg",
		rating: 4.7,
		reviews: 678,
		capacity: "5L",
		presets: 9,
		features: ["5L Capacity", "Turbo Mode", "9 Presets", "Quick Preheat"],
		badge: "Fast Cook",
		wattage: "1850W",
		tempRange: "80-220°C",
		amazonLink: "https://www.amazon.com",
		description:
			"The AirChef Turbo 5L is engineered for speed without sacrificing quality, making it perfect for busy families who need dinner on the table fast. The innovative Turbo Mode increases air circulation and heat intensity, reducing cooking times by up to 30% compared to standard air fryers. Quick preheat technology means you can start cooking in just 2 minutes, eliminating the long wait times associated with traditional ovens. The 5-liter capacity is ideal for families of 3-4, while 9 optimized presets ensure perfect results even when you're in a hurry. The powerful 1850W heating element provides rapid, even cooking, and the streamlined design makes operation simple even when you're rushing. If time is precious and you need an air fryer that can keep up with your busy lifestyle, the Turbo 5L is your ideal solution.",
		specifications: {
			Brand: "AirChef",
			Model: "Turbo 5L",
			Capacity: "5 Liters (5.3 Quarts)",
			"Special Feature": "Turbo Mode",
			"Cooking Presets": "9 Presets",
			"Quick Preheat": "Yes - Under 2 Minutes",
			"Power Output": "1850 Watts",
			"Temperature Range": "80°C - 220°C (176°F - 428°F)",
			Dimensions: "12 x 11 x 12 inches",
			"Turbo Mode": "30% Faster Cooking with Enhanced Air Circulation",
			"Preheat Time": "Under 2 Minutes",
			"Preset Functions":
				"Turbo Fries, Quick Chicken, Fast Steak, Speed Fish, Express Pizza, Rapid Vegetables, Quick Bake, Fast Roast, Instant Reheat",
			Display: "Quick-Access Digital Display",
			"Basket Material": "High-Conductivity Non-Stick",
			"Cooking Technology": "Turbo Rapid Air Circulation System",
			"Safety Features": "Rapid Cool-Down, Auto Shut-Off",
			Warranty: "2 Years Turbo Warranty",
			"Ideal For": "Fast Cooking, Busy Families, Quick Meals",
		},
	},
	{
		slug: "airchef-deluxe-8l",
		name: "AirChef Deluxe 8L",
		price: "$199.99",
		image: "/large-professional-multicooker-8-liter-stainless-s.jpg",
		rating: 4.9,
		reviews: 1156,
		capacity: "8L",
		presets: 14,
		features: ["8L Capacity", "Rotisserie", "14 Presets", "Window View"],
		badge: "Deluxe",
		wattage: "1900W",
		tempRange: "50-230°C",
		amazonLink: "https://www.amazon.com",
		description:
			"The AirChef Deluxe 8L is the ultimate premium air fryer for culinary enthusiasts who demand the best. The built-in rotisserie function allows you to prepare perfectly roasted chicken, kebabs, and other rotating foods with restaurant-quality results. The large viewing window lets you monitor your food without opening the basket, maintaining optimal cooking conditions. With an impressive 8-liter capacity, you can easily prepare meals for 6-8 people, making it perfect for entertaining. Fourteen versatile presets cover everything from basic air frying to advanced techniques, while the extended temperature range provides maximum cooking flexibility. Premium construction with stainless steel accents and a sleek design makes this air fryer a stunning addition to any kitchen. If you're passionate about cooking and want an air fryer that can handle any culinary challenge, the Deluxe 8L is your perfect companion.",
		specifications: {
			Brand: "AirChef",
			Model: "Deluxe 8L",
			Capacity: "8 Liters (8.5 Quarts)",
			"Special Feature": "Rotisserie",
			"Cooking Presets": "14 Presets",
			"Window View": "Yes - Large Viewing Window",
			"Power Output": "1900 Watts",
			"Temperature Range": "50°C - 230°C (122°F - 446°F)",
			Dimensions: "15 x 14 x 14 inches",
			"Preset Functions":
				"Fries, Chicken, Steak, Shrimp, Fish, Pizza, Vegetables, Bake, Roast, Rotisserie, Dehydrate, Broil, Reheat, Keep Warm",
			Rotisserie: "Motorized Rotisserie Spit with Forks",
			"Viewing Window": "Large Tempered Glass Window with Interior LED Light",
			Display: "Premium Digital Display with Backlight",
			"Basket Material": "Premium Stainless Steel with Non-Stick Coating",
			Construction: "Stainless Steel Exterior with Premium Finish",
			"Safety Features": "Auto Shut-Off, Cool-Touch Handle, Window Lock",
			Warranty: "3 Years Deluxe Warranty",
			"Ideal For": "Deluxe Cooking, Rotisserie, Premium Features",
		},
	},
	{
		slug: "airchef-eco-4-5l",
		name: "AirChef Eco 4.5L",
		price: "$109.99",
		image: "/compact-multicooker-6-liter-red.jpg",
		rating: 4.7,
		reviews: 534,
		capacity: "4.5L",
		presets: 7,
		features: ["4.5L Capacity", "Energy Saving", "7 Presets", "Eco Mode"],
		badge: "Eco-Friendly",
		wattage: "1500W",
		tempRange: "80-200°C",
		amazonLink: "https://www.amazon.com",
		description:
			"The AirChef Eco 4.5L is the environmentally conscious choice for sustainable cooking without compromising performance. This innovative air fryer features an advanced energy-saving mode that reduces power consumption by up to 25% compared to standard models, helping you reduce your carbon footprint while saving on electricity bills. The basket is made from eco-friendly materials that are free from PFOA and other harmful chemicals, ensuring safe and healthy cooking for your family. The 4.5-liter capacity is perfect for small to medium families, while 7 cooking presets cover all essential air frying needs. The exterior is constructed from recycled materials, and the packaging is 100% recyclable. For environmentally conscious consumers who want to make sustainable choices without sacrificing convenience or performance, the Eco 4.5L is the ideal air fryer.",
		specifications: {
			Brand: "AirChef",
			Model: "Eco 4.5L",
			Capacity: "4.5 Liters (4.8 Quarts)",
			"Special Feature": "Energy Saving",
			"Cooking Presets": "7 Presets",
			"Eco Mode": "Yes - Intelligent Energy-Saving Algorithm",
			"Power Output": "1500 Watts (Energy Efficient)",
			"Energy Savings": "Up to 25% Less Energy Consumption",
			"Temperature Range": "80°C - 200°C (176°F - 392°F)",
			Dimensions: "11 x 11 x 12 inches",
			"Eco Certifications": "Energy Star Certified, PFOA-Free, BPA-Free",
			"Preset Functions": "Eco Fries, Chicken, Fish, Vegetables, Bake, Roast, Reheat",
			"Basket Material": "Eco-Ceramic Non-Stick Coating (Chemical-Free)",
			Display: "Energy-Efficient LED Display",
			Construction: "50% Recycled Materials",
			Packaging: "100% Recyclable, Plastic-Free",
			"Safety Features": "Auto Shut-Off, Eco-Safe Materials",
			Warranty: "2 Years Eco Warranty",
			"Ideal For": "Eco-Conscious Consumers, Energy Efficiency, Sustainable Cooking",
		},
	},
]
